# Generated by Django 5.1.4 on 2024-12-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_price_per_ticket'),
        ('payments', '0003_initial'),
        ('properties', '0003_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='vehicle_booking',
        ),
        migrations.AddField(
            model_name='payment',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.flight'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card')], max_length=20),
        ),
        migrations.CreateModel(
            name='BookingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights', models.PositiveBigIntegerField(default=1)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
            ],
        ),
    ]
