# Generated by Django 4.2 on 2024-12-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_airline_flight_airline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="airline_name",
        ),
    ]
