# Generated by Django 5.1.4 on 2024-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_flight_airline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price_per_ticket',
            field=models.PositiveBigIntegerField(),
        ),
    ]
